export const SECTORS = [
  'Hydropower',
  'Microfinance',
  'Insurance',
  'Development Bank',
  'Commercial Bank',
  'Manufacturing',
  'Hotels & Tourism',
  'Investment',
  'Others'
];

export const BASE_RATES = {
  'Hydropower': 70,
  'Microfinance': 45,
  'Insurance': 55,
  'Development Bank': 50,
  'Commercial Bank': 40,
  'Manufacturing': 60,
  'Hotels & Tourism': 65,
  'Investment': 50,
  'Others': 50
};

export const DUMMY_IPOS = [
  {
    id: '1',
    name: 'Upper Tamakoshi Hydropower',
    nameNP: 'माथिल्लो तामाकोशी जलविद्युत',
    sector: 'Hydropower',
    type: 'IPO',
    category: 'General Public',
    issuedUnits: 15000000,
    price: 100,
    openDate: '2023-10-15',
    closeDate: '2023-10-19',
    oversubscription: 4.5,
    allotmentRate: 85,
    listingPrice: 224,
    listingGain: 124
  },
  {
    id: '2',
    name: 'Nabil Bank Debenture 2085',
    nameNP: 'नबिल बैंक ऋणपत्र २०८५',
    sector: 'Commercial Bank',
    type: 'Debenture',
    category: 'General Public',
    issuedUnits: 3000000,
    price: 1000,
    openDate: '2024-01-05',
    closeDate: '2024-01-10',
    oversubscription: 1.2,
    allotmentRate: 100,
    listingPrice: 1000,
    listingGain: 0
  },
  {
    id: '3',
    name: 'Sarbottam Cement',
    nameNP: 'सर्वोत्तम सिमेन्ट',
    sector: 'Manufacturing',
    type: 'IPO',
    category: 'General Public',
    issuedUnits: 6000000,
    price: 360,
    openDate: '2024-01-25',
    closeDate: '2024-01-30',
    oversubscription: 15.5,
    allotmentRate: 12,
    listingPrice: 520,
    listingGain: 44
  }
];

export const TRANSLATIONS = {
  EN: {
    home: 'Home',
    predictor: 'Predictor',
    history: 'IPO History',
    education: 'Education',
    about: 'About',
    admin: 'Admin',
    heroTitle: 'Will You Get the IPO? Find Out Before the Result.',
    heroSub: 'Nepal\'s smartest IPO allotment probability at one click.',
    checkChances: 'Check My Allotment Chances',
    howItWorks: 'How It Works',
    step1: 'Enter IPO Details',
    step2: 'Our Algorithm Analyzes Data',
    step3: 'Get Your Probability Score',
    recentResults: 'Recent IPO Results',
    testimonials: 'What Investors Say',
    selectIPO: 'Select the IPO',
    appDetails: 'Application Details',
    predict: 'Predict My Allotment',
    analyzing: 'Our algorithm is analyzing 500+ historical IPOs...',
    verdictLow: 'Low Chance',
    verdictMod: 'Moderate Chance',
    verdictGood: 'Good Chance',
    verdictHigh: 'Very High Chance',
    expectedKitta: 'Expected Kitta You May Receive',
    shareFB: 'Share on Facebook',
    tips: 'Apply Tips',
    searchPlaceholder: 'Search by company name...',
    mission: 'Our Mission',
    contactUs: 'Contact Us',
    disclaimer: 'The IPO allotment probabilities shown here are only estimates based on available data. Actual results may differ due to the official random allotment process. This site is for informational and fun purposes only which gives just idea about your chance of allotment and does not provide financial advice.',
    commentLow: 'Ouch! Looks like the luck is on vacation. Better luck next time! 🤞',
    commentMod: "Not bad! You're in the race. Keep your fingers crossed! 🤞",
    commentGood: 'Looking good! The stars might be aligning for you. Good luck! ✨',
    commentHigh: "Wow! You're almost there. Get ready to celebrate! 🎉",
    wish: 'Best wishes for your result!',
    predictorTitle: 'IPO Allotment Predictor',
    predictorSub: 'Enter details below to calculate your statistical probability of allotment.',
    selectCompany: 'Select the Company',
    predictNow: 'Predict Now',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    disclaimerPage: 'Disclaimer',
    funnyCommentLow: 'Ouch! Looks like the luck is on vacation. Better luck next time! 🤞',
    funnyCommentMod: "Not bad! You're in the race. Keep your fingers crossed! 🤞",
    funnyCommentGood: 'Looking good! The stars might be aligning for you. Good luck! ✨',
    funnyCommentHigh: "Wow! You're almost there. Get ready to celebrate! 🎉",
    bestWishes: 'Best wishes for your result!',
    wish: 'Good Luck! 🍀',
    shareResult: 'Share Result',
    downloadCard: 'Download Card',
    backToForm: 'Back to Form',
    resultFor: 'Prediction Result for',
    oversubscriptionChecker: 'Oversubscription Checker',
    selectCompany: 'Select Company',
    checkOversubscription: 'Check Oversubscription',
    oversubscribedBy: 'Oversubscribed by',
    times: 'times',
    totalIssuedUnits: 'Total Issued Units',
    totalAppliedUnits: 'Total Applied Units',
    lastUpdated: 'Data last updated',
    dontKnowOversubscription: "Don't know oversubscription? Click here to check.",
    autoFill: 'Auto-Fill',
    loading: 'Loading...'
  },
  NP: {
    home: 'होम',
    predictor: 'प्रेडिक्टर',
    history: 'IPO इतिहास',
    education: 'शिक्षा',
    about: 'हाम्रो बारेमा',
    admin: 'एडमिन',
    heroTitle: 'के तपाईलाई IPO पर्ला? नतिजा अगावै थाहा पाउनुहोस्।',
    heroSub: 'नेपालको सबै IPO को बाँडफाँड सम्भावना एक क्लिकमा।',
    checkChances: 'मेरो सम्भावना जाँच गर्नुहोस्',
    howItWorks: 'यसले कसरी काम गर्छ',
    step1: 'IPO विवरणहरू भर्नुहोस्',
    step2: 'हाम्रो एल्गोरिदमले डेटा विश्लेषण गर्दछ',
    step3: 'तपाईको सम्भाव्यता स्कोर प्राप्त गर्नुहोस्',
    recentResults: 'भर्खरका IPO नतिजाहरू',
    testimonials: 'लगानीकर्ताहरू के भन्छन्',
    selectIPO: 'IPO छान्नुहोस्',
    appDetails: 'आवेदन विवरणहरू',
    predict: 'मेरो बाँडफाँड भविष्यवाणी गर्नुहोस्',
    analyzing: 'हाम्रो एल्गोरिदमले ५००+ ऐतिहासिक IPO हरू विश्लेषण गर्दैछ...',
    verdictLow: 'कम सम्भावना',
    verdictMod: 'मध्यम सम्भावना',
    verdictGood: 'राम्रो सम्भावना',
    verdictHigh: 'धेरै उच्च सम्भावना',
    expectedKitta: 'तपाईले प्राप्त गर्न सक्ने अपेक्षित कित्ता',
    shareFB: 'फेसबुकमा सेयर गर्नुहोस्',
    tips: 'आवेदन सुझावहरू',
    searchPlaceholder: 'कम्पनीको नाम खोज्नुहोस्...',
    mission: 'हाम्रो लक्ष्य',
    contactUs: 'हामीलाई सम्पर्क गर्नुहोस',
    disclaimer: 'यहाँ देखाइएको IPO बाँडफाँडको सम्भावना उपलब्ध तथ्याङ्कहरूमा आधारित अनुमान मात्र हो। आधिकारिक अनियमित बाँडफाँड प्रक्रियाको कारण वास्तविक नतिजाहरू फरक हुन सक्छन्। यो साइट जानकारीमूलक र मनोरञ्जनका लागि मात्र हो जसले तपाईको बाँडफाँडको सम्भावनाको बारेमा मात्र जानकारी दिन्छ र वित्तीय सल्लाह प्रदान गर्दैन।',
    commentLow: 'ओहो! भाग्य बिदामा गएको जस्तो छ। अर्को पटक प्रयास गर्नुहोला! 🤞',
    commentMod: 'ठिकै छ! तपाई दौडमा हुनुहुन्छ। औंलाहरू क्रस गरेर बस्नुहोस्! 🤞',
    commentGood: 'राम्रो देखिँदैछ! ताराहरू तपाईको पक्षमा हुन सक्छन्। शुभकामना! ✨',
    commentHigh: 'वाह! तपाई लगभग त्यहाँ हुनुहुन्छ। उत्सव मनाउन तयार हुनुहोस्! 🎉',
    wish: 'तपाईको नतिजाको लागि शुभकामना!',
    predictorTitle: 'IPO बाँडफाँड प्रेडिक्टर',
    predictorSub: 'बाँडफाँडको सम्भावना गणना गर्न तलको विवरणहरू भर्नुहोस्।',
    selectCompany: 'कम्पनी छान्नुहोस्',
    predictNow: 'भविष्यवाणी गर्नुहोस्',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवाका सर्तहरू',
    disclaimerPage: 'अस्वीकरण',
    funnyCommentLow: 'ओहो! भाग्य बिदामा गएको जस्तो छ। अर्को पटक प्रयास गर्नुहोला! 🤞',
    funnyCommentMod: 'ठिकै छ! तपाई दौडमा हुनुहुन्छ। औंलाहरू क्रस गरेर बस्नुहोस्! 🤞',
    funnyCommentGood: 'राम्रो देखिँदैछ! ताराहरू तपाईको पक्षमा हुन सक्छन्। शुभकामना! ✨',
    funnyCommentHigh: 'वाह! तपाई लगभग त्यहाँ हुनुहुन्छ। उत्सव मनाउन तयार हुनुहोस्! 🎉',
    bestWishes: 'तपाईको नतिजाको लागि शुभकामना!',
    wish: 'शुभकामना! 🍀',
    shareResult: 'नतिजा सेयर गर्नुहोस्',
    downloadCard: 'कार्ड डाउनलोड गर्नुहोस्',
    backToForm: 'फारममा फर्कनुहोस्',
    resultFor: 'को लागि भविष्यवाणी नतिजा',
    oversubscriptionChecker: 'ओभरसब्सक्रिप्शन चेकर',
    selectCompany: 'कम्पनी छान्नुहोस्',
    checkOversubscription: 'ओभरसब्सक्रिप्शन जाँच गर्नुहोस्',
    oversubscribedBy: 'ओभरसब्सक्राइब गरिएको छ',
    times: 'गुणा',
    totalIssuedUnits: 'कुल जारी इकाइहरू',
    totalAppliedUnits: 'कुल आवेदन गरिएका इकाइहरू',
    lastUpdated: 'तथ्याङ्क अन्तिम पटक अपडेट गरिएको',
    dontKnowOversubscription: 'ओभरसब्सक्रिप्शन थाहा छैन? जाँच गर्न यहाँ क्लिक गर्नुहोस्।',
    autoFill: 'अटो-फिल',
    loading: 'लोड हुँदैछ...'
  }
};
